# Generated by Django 4.2.3 on 2023-07-12 20:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('employeeID', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ZA', unique=True)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('contractHours', models.DecimalField(decimal_places=2, max_digits=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('profileImage', models.ImageField(upload_to='identification/profiles/')),
                ('working_status', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_security', models.BooleanField(default=False)),
            ],
        ),
    ]
