# Generated by Django 4.2.3 on 2023-07-14 08:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='emergency_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ZA', unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
