# Generated by Django 4.2.3 on 2023-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemodel',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
